version: "3.8"

services:
  catalogo:
    build: .
    container_name: catalogo
    restart: unless-stopped

    depends_on:
      - postgres

    ports:
      - "8080:8080"

    environment:
      POSTGRES_CONN: postgresql://catalogo:{{postgress_password}}@postgres:5432/catalogo

      JWT_TOKEN: "{{}}"
      JWT_EXPIRATION_S: 3600
      UPLOAD: "/app/uploads"

      DEV: "False"

      HOST: "0.0.0.0"
      PORT: "8080"

    volumes:
      - ./uploads:/app/uploads

    restart: unless-stopped

  postgres:
    image: postgres:17
    container_name: catalogo-postgres
    restart: unless-stopped

    environment:
      POSTGRES_USER: catalogo
      POSTGRES_PASSWORD: {{postgress_password}}
      POSTGRES_DB: catalogo

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: