# Exeptions User
class UserExists(Exception): ...
class UserNotFound(Exception): ...
class InvalidUser(Exception): ...
# Token Exeptions
class TokenExpired(Exception): ...
class TokenInvalid(Exception): ...